CREATE TYPE "user_role" AS ENUM ('ADMIN', 'USER');
CREATE TYPE "transaction_status" AS ENUM ('DRAFT', 'COMPLETED', 'CANCELLED');
CREATE TYPE "transaction_type" AS ENUM ('STOCK_ADJUSTMENT_IN', 'STOCK_RELEASE', 'STOCK_RETURN');
CREATE TYPE "movement_purpose" AS ENUM ('ORIGINAL', 'CANCELLATION_REVERSAL');

CREATE TABLE "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" TEXT NOT NULL,
    "display_name" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "role" "user_role" NOT NULL DEFAULT 'USER',
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "models" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "model_name" TEXT NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "customers" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "customer_name" TEXT NOT NULL,
    "address" TEXT,
    "contact_person" TEXT,
    "contact_number" TEXT,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "service_tags" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "model_id" BIGINT NOT NULL,
    "customer_id" BIGINT,
    "service_tag" TEXT NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "devices" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "device_name" TEXT NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "device_details" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "device_id" BIGINT NOT NULL,
    "part_number" TEXT NOT NULL,
    "dpn" TEXT,
    "specification" TEXT NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "racks" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "rack_code" TEXT NOT NULL,
    "rack_name" TEXT NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "transaction_counters" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "transaction_type" "transaction_type" NOT NULL,
    "year_month" VARCHAR(6) NOT NULL,
    "last_number" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "stock_adjustment_ins" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "transaction_number" TEXT NOT NULL,
    "transaction_date" DATE NOT NULL,
    "customer_id" BIGINT,
    "notes" TEXT,
    "status" "transaction_status" NOT NULL DEFAULT 'DRAFT',
    "created_by" BIGINT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "stock_adjustment_in_details" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "stock_adjustment_in_id" BIGINT NOT NULL,
    "device_detail_id" BIGINT NOT NULL,
    "rack_id" BIGINT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "notes" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "sai_quantity_positive" CHECK ("quantity" > 0)
);

CREATE TABLE "stock_releases" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "transaction_number" TEXT NOT NULL,
    "release_date" DATE NOT NULL,
    "engineer_name" TEXT NOT NULL,
    "customer_id" BIGINT NOT NULL,
    "model_id" BIGINT,
    "service_tag_id" BIGINT,
    "reference_number" TEXT,
    "notes" TEXT,
    "status" "transaction_status" NOT NULL DEFAULT 'DRAFT',
    "created_by" BIGINT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "stock_release_details" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "stock_release_id" BIGINT NOT NULL,
    "device_detail_id" BIGINT NOT NULL,
    "rack_id" BIGINT NOT NULL,
    "released_quantity" INTEGER NOT NULL,
    "notes" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "srl_quantity_positive" CHECK ("released_quantity" > 0)
);

CREATE TABLE "stock_returns" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "transaction_number" TEXT NOT NULL,
    "return_date" DATE NOT NULL,
    "stock_release_id" BIGINT NOT NULL,
    "notes" TEXT,
    "status" "transaction_status" NOT NULL DEFAULT 'DRAFT',
    "created_by" BIGINT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "stock_return_details" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "stock_return_id" BIGINT NOT NULL,
    "stock_release_detail_id" BIGINT NOT NULL,
    "destination_rack_id" BIGINT NOT NULL,
    "return_quantity" INTEGER NOT NULL,
    "notes" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "srt_quantity_positive" CHECK ("return_quantity" > 0)
);

CREATE TABLE "stock_movements" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "device_detail_id" BIGINT NOT NULL,
    "rack_id" BIGINT NOT NULL,
    "customer_id" BIGINT,
    "transaction_type" "transaction_type" NOT NULL,
    "transaction_id" BIGINT NOT NULL,
    "transaction_detail_id" BIGINT NOT NULL,
    "transaction_number" TEXT NOT NULL,
    "transaction_date" DATE NOT NULL,
    "engineer_name" TEXT,
    "quantity_in" INTEGER NOT NULL DEFAULT 0,
    "quantity_out" INTEGER NOT NULL DEFAULT 0,
    "movement_purpose" "movement_purpose" NOT NULL DEFAULT 'ORIGINAL',
    "reversal_of_id" BIGINT,
    "created_by" BIGINT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "stock_movement_one_side_positive" CHECK (
        ("quantity_in" > 0 AND "quantity_out" = 0)
        OR ("quantity_out" > 0 AND "quantity_in" = 0)
    ),
    CONSTRAINT "stock_movement_reversal_target_required" CHECK (
        ("movement_purpose" = 'ORIGINAL' AND "reversal_of_id" IS NULL)
        OR (
            "movement_purpose" = 'CANCELLATION_REVERSAL'
            AND "reversal_of_id" IS NOT NULL
        )
    )
);

CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
CREATE UNIQUE INDEX "users_email_ci_key" ON "users" (lower("email"));
CREATE UNIQUE INDEX "models_model_name_key" ON "models" ("model_name");
CREATE UNIQUE INDEX "models_model_name_ci_key" ON "models" (lower("model_name"));
CREATE UNIQUE INDEX "service_tags_service_tag_key" ON "service_tags" ("service_tag");
CREATE UNIQUE INDEX "service_tags_service_tag_ci_key" ON "service_tags" (lower("service_tag"));
CREATE UNIQUE INDEX "customers_customer_name_key" ON "customers" ("customer_name");
CREATE UNIQUE INDEX "customers_customer_name_ci_key" ON "customers" (lower("customer_name"));
CREATE UNIQUE INDEX "devices_device_name_key" ON "devices" ("device_name");
CREATE UNIQUE INDEX "devices_device_name_ci_key" ON "devices" (lower("device_name"));
CREATE UNIQUE INDEX "racks_rack_code_key" ON "racks" ("rack_code");
CREATE UNIQUE INDEX "racks_rack_code_ci_key" ON "racks" (lower("rack_code"));
CREATE UNIQUE INDEX "device_details_identity_key"
    ON "device_details" ("device_id", lower("part_number"), lower("dpn")) NULLS NOT DISTINCT;

CREATE INDEX "service_tags_model_id_idx" ON "service_tags" ("model_id");
CREATE INDEX "service_tags_customer_id_idx" ON "service_tags" ("customer_id");
CREATE INDEX "device_details_device_id_idx" ON "device_details" ("device_id");
CREATE UNIQUE INDEX "transaction_counters_type_year_month_key" ON "transaction_counters" ("transaction_type", "year_month");
CREATE UNIQUE INDEX "stock_adjustment_ins_transaction_number_key" ON "stock_adjustment_ins" ("transaction_number");
CREATE INDEX "stock_adjustment_ins_customer_date_idx" ON "stock_adjustment_ins" ("customer_id", "transaction_date");
CREATE INDEX "stock_adjustment_ins_status_date_idx" ON "stock_adjustment_ins" ("status", "transaction_date");
CREATE INDEX "stock_adjustment_ins_created_by_idx" ON "stock_adjustment_ins" ("created_by");
CREATE INDEX "sai_details_header_id_idx" ON "stock_adjustment_in_details" ("stock_adjustment_in_id");
CREATE INDEX "sai_details_device_rack_idx" ON "stock_adjustment_in_details" ("device_detail_id", "rack_id");
CREATE UNIQUE INDEX "stock_releases_transaction_number_key" ON "stock_releases" ("transaction_number");
CREATE INDEX "stock_releases_customer_date_idx" ON "stock_releases" ("customer_id", "release_date");
CREATE INDEX "stock_releases_model_id_idx" ON "stock_releases" ("model_id");
CREATE INDEX "stock_releases_service_tag_id_idx" ON "stock_releases" ("service_tag_id");
CREATE INDEX "stock_releases_status_date_idx" ON "stock_releases" ("status", "release_date");
CREATE INDEX "stock_releases_created_by_idx" ON "stock_releases" ("created_by");
CREATE INDEX "stock_release_details_header_id_idx" ON "stock_release_details" ("stock_release_id");
CREATE INDEX "stock_release_details_device_rack_idx" ON "stock_release_details" ("device_detail_id", "rack_id");
CREATE UNIQUE INDEX "stock_returns_transaction_number_key" ON "stock_returns" ("transaction_number");
CREATE INDEX "stock_returns_release_status_idx" ON "stock_returns" ("stock_release_id", "status");
CREATE INDEX "stock_returns_status_date_idx" ON "stock_returns" ("status", "return_date");
CREATE INDEX "stock_returns_created_by_idx" ON "stock_returns" ("created_by");
CREATE INDEX "stock_return_details_header_id_idx" ON "stock_return_details" ("stock_return_id");
CREATE INDEX "stock_return_details_release_detail_idx" ON "stock_return_details" ("stock_release_detail_id", "stock_return_id");
CREATE INDEX "stock_return_details_destination_rack_id_idx" ON "stock_return_details" ("destination_rack_id");
CREATE UNIQUE INDEX "stock_movements_source_identity_key" ON "stock_movements" ("transaction_type", "transaction_detail_id", "movement_purpose");
CREATE UNIQUE INDEX "stock_movements_one_reversal_per_original_key"
    ON "stock_movements" ("reversal_of_id")
    WHERE "reversal_of_id" IS NOT NULL;
CREATE INDEX "stock_movements_balance_report_idx" ON "stock_movements" ("device_detail_id", "rack_id", "transaction_date", "created_at");
CREATE INDEX "stock_movements_customer_report_idx" ON "stock_movements" ("customer_id", "transaction_date", "created_at");
CREATE INDEX "stock_movements_transaction_lookup_idx" ON "stock_movements" ("transaction_number", "transaction_date");
CREATE INDEX "stock_movements_transaction_source_idx" ON "stock_movements" ("transaction_type", "transaction_id");
CREATE INDEX "stock_movements_reversal_of_id_idx" ON "stock_movements" ("reversal_of_id");
CREATE INDEX "stock_movements_created_by_idx" ON "stock_movements" ("created_by");

ALTER TABLE "service_tags" ADD CONSTRAINT "service_tags_model_id_fkey" FOREIGN KEY ("model_id") REFERENCES "models" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "service_tags" ADD CONSTRAINT "service_tags_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "device_details" ADD CONSTRAINT "device_details_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "devices" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_adjustment_ins" ADD CONSTRAINT "stock_adjustment_ins_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_adjustment_ins" ADD CONSTRAINT "stock_adjustment_ins_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_adjustment_in_details" ADD CONSTRAINT "stock_adjustment_in_details_stock_adjustment_in_id_fkey" FOREIGN KEY ("stock_adjustment_in_id") REFERENCES "stock_adjustment_ins" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_adjustment_in_details" ADD CONSTRAINT "stock_adjustment_in_details_device_detail_id_fkey" FOREIGN KEY ("device_detail_id") REFERENCES "device_details" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_adjustment_in_details" ADD CONSTRAINT "stock_adjustment_in_details_rack_id_fkey" FOREIGN KEY ("rack_id") REFERENCES "racks" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_releases" ADD CONSTRAINT "stock_releases_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_releases" ADD CONSTRAINT "stock_releases_model_id_fkey" FOREIGN KEY ("model_id") REFERENCES "models" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_releases" ADD CONSTRAINT "stock_releases_service_tag_id_fkey" FOREIGN KEY ("service_tag_id") REFERENCES "service_tags" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_releases" ADD CONSTRAINT "stock_releases_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_release_details" ADD CONSTRAINT "stock_release_details_stock_release_id_fkey" FOREIGN KEY ("stock_release_id") REFERENCES "stock_releases" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_release_details" ADD CONSTRAINT "stock_release_details_device_detail_id_fkey" FOREIGN KEY ("device_detail_id") REFERENCES "device_details" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_release_details" ADD CONSTRAINT "stock_release_details_rack_id_fkey" FOREIGN KEY ("rack_id") REFERENCES "racks" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_returns" ADD CONSTRAINT "stock_returns_stock_release_id_fkey" FOREIGN KEY ("stock_release_id") REFERENCES "stock_releases" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_returns" ADD CONSTRAINT "stock_returns_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_return_details" ADD CONSTRAINT "stock_return_details_stock_return_id_fkey" FOREIGN KEY ("stock_return_id") REFERENCES "stock_returns" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_return_details" ADD CONSTRAINT "stock_return_details_stock_release_detail_id_fkey" FOREIGN KEY ("stock_release_detail_id") REFERENCES "stock_release_details" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_return_details" ADD CONSTRAINT "stock_return_details_destination_rack_id_fkey" FOREIGN KEY ("destination_rack_id") REFERENCES "racks" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_device_detail_id_fkey" FOREIGN KEY ("device_detail_id") REFERENCES "device_details" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_rack_id_fkey" FOREIGN KEY ("rack_id") REFERENCES "racks" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_reversal_of_id_fkey" FOREIGN KEY ("reversal_of_id") REFERENCES "stock_movements" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE FUNCTION "validate_stock_movement_reversal"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    original "stock_movements"%ROWTYPE;
BEGIN
    IF NEW."movement_purpose" <> 'CANCELLATION_REVERSAL' THEN
        RETURN NEW;
    END IF;

    SELECT *
    INTO original
    FROM "stock_movements"
    WHERE "id" = NEW."reversal_of_id"
    FOR KEY SHARE;

    IF NOT FOUND
       OR original."movement_purpose" <> 'ORIGINAL'
       OR original."reversal_of_id" IS NOT NULL THEN
        RAISE EXCEPTION 'stock movement reversal must reference an original movement'
            USING ERRCODE = '23514';
    END IF;

    IF ROW(
        NEW."device_detail_id",
        NEW."rack_id",
        NEW."customer_id",
        NEW."transaction_type",
        NEW."transaction_id",
        NEW."transaction_detail_id",
        NEW."transaction_number",
        NEW."transaction_date",
        NEW."engineer_name"
    ) IS DISTINCT FROM ROW(
        original."device_detail_id",
        original."rack_id",
        original."customer_id",
        original."transaction_type",
        original."transaction_id",
        original."transaction_detail_id",
        original."transaction_number",
        original."transaction_date",
        original."engineer_name"
    )
       OR NEW."quantity_in" <> original."quantity_out"
       OR NEW."quantity_out" <> original."quantity_in" THEN
        RAISE EXCEPTION 'stock movement reversal must be equal and opposite for the same stock and source dimensions'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER "stock_movements_validate_reversal"
BEFORE INSERT ON "stock_movements"
FOR EACH ROW
EXECUTE FUNCTION "validate_stock_movement_reversal"();

CREATE FUNCTION "reject_stock_movement_mutation"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'stock movements are immutable'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER "stock_movements_reject_mutation"
BEFORE UPDATE OR DELETE ON "stock_movements"
FOR EACH ROW
EXECUTE FUNCTION "reject_stock_movement_mutation"();
